<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Jadwal Mengajar - {{ $teacher->name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        h1 {
            text-align: center;
            color: #2563eb;
            margin-bottom: 20px;
        }
        .header-info {
            text-align: center;
            margin-bottom: 30px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f7ff;
            font-weight: bold;
        }
        .day-header {
            background-color: #e0e7ff;
            font-size: 16px;
            font-weight: bold;
            padding: 10px;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
        
        /* Auto print when loaded if this is a PDF download */
        @if(isset($isPdfDownload) && $isPdfDownload)
        @media print {
            .no-print {
                display: none;
            }
        }
        @endif
    </style>
    
    @if(isset($isPdfDownload) && $isPdfDownload)
    <script>
        window.onload = function() {
            window.print();
        }
    </script>
    @endif
</head>
<body>
    <div class="no-print" style="text-align: center; margin-bottom: 20px;">
        <button onclick="window.print();" style="padding: 10px 20px; background: #4a60a8; color: white; border: none; border-radius: 4px; cursor: pointer;">
            Cetak Dokumen
        </button>
        <button onclick="window.close();" style="padding: 10px 20px; background: #6b7280; color: white; border: none; border-radius: 4px; cursor: pointer; margin-left: 10px;">
            Tutup
        </button>
    </div>

    <h1>Jadwal Mengajar</h1>
    
    <div class="header-info">
        <p>
            <strong>Guru:</strong> {{ $teacher->name }}<br>
            <strong>Tanggal Cetak:</strong> {{ now()->format('d F Y H:i') }}
        </p>
    </div>
    
    @foreach($schedulesByDay as $day => $daySchedules)
        <div class="day-header">{{ $day }}</div>
        <table>
            <thead>
                <tr>
                    <th width="5%">No</th>
                    <th width="25%">Mata Pelajaran</th>
                    <th width="20%">Kelas</th>
                    <th width="20%">Jam</th>
                    <th width="30%">Ruangan</th>
                </tr>
            </thead>
            <tbody>
                @foreach($daySchedules as $index => $schedule)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $schedule->subject->name ?? 'N/A' }}</td>
                        <td>{{ $schedule->classroom->name ?? 'N/A' }}</td>
                        <td>{{ $schedule->start_time }} - {{ $schedule->end_time }}</td>
                        <td>{{ $schedule->room ?? 'Belum ditentukan' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endforeach
    
    <div class="footer">
        <p>SMAN 1 - Generated by GIRSIP System - {{ now()->format('d/m/Y H:i:s') }}</p>
    </div>
</body>
</html>
